name: Claude Code Official (via Cynosure Bridge)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]
  workflow_dispatch:
    inputs:
      task:
        description: 'Задача для Claude'
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  # Запуск Cynosure Bridge как прокси-сервер
  start-proxy:
    runs-on: ubuntu-latest
    outputs:
      proxy-url: ${{ steps.proxy.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Project
        run: npm run build
        
      - name: Start Cynosure Bridge
        id: proxy
        run: |
          echo "🚀 Запускаем Cynosure Bridge на порту 3000..."
          
          # Запускаем сервер в фоне
          PORT=3000 npm start &
          PROXY_PID=$!
          
          # Ждем запуска сервера
          sleep 10
          
          # Проверяем что сервер запустился
          if curl -f http://localhost:3000/health > /dev/null 2>&1; then
            echo "✅ Cynosure Bridge запущен успешно"
            echo "url=http://localhost:3000" >> $GITHUB_OUTPUT
            echo "pid=$PROXY_PID" >> $GITHUB_OUTPUT
          else
            echo "❌ Ошибка запуска Cynosure Bridge"
            exit 1
          fi
          
          # Тестируем OpenAI API совместимость
          echo "🧪 Тестируем API совместимость..."
          curl -X POST http://localhost:3000/v1/chat/completions \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer dummy-key" \
            -d '{
              "model": "gpt-4",
              "messages": [{"role": "user", "content": "Test connection"}],
              "max_tokens": 10
            }' || echo "Тест API завершен"
        
        env:
          NODE_ENV: production

  # Официальный Claude Code Action через прокси
  claude-response:
    needs: start-proxy
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'pull_request_review' && github.event.review.state == 'commented')
    
    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.CLAUDE_GITHUB_APP_ID }}
          private-key: ${{ secrets.CLAUDE_GITHUB_APP_PRIVATE_KEY }}
          
      - name: Setup Custom OpenAI Endpoint
        run: |
          echo "🔧 Настраиваем кастомный OpenAI endpoint через Cynosure Bridge"
          echo "OPENAI_API_BASE=${{ needs.start-proxy.outputs.proxy-url }}" >> $GITHUB_ENV
          echo "OPENAI_BASE_URL=${{ needs.start-proxy.outputs.proxy-url }}" >> $GITHUB_ENV
          
      - name: Claude Code Action (Official)
        uses: anthropics/claude-code-action@beta
        with:
          # Используем dummy key так как аутентификация проходит через Claude MAX
          anthropic_api_key: "dummy-key-for-max-subscription"
          github_token: ${{ steps.app-token.outputs.token }}
          
          # Опциональные настройки
          trigger_phrase: "@claude"
          max_turns: "5"
          timeout_minutes: 30
          
          # Кастомные инструкции для работы через прокси
          custom_instructions: |
            Ты работаешь через Cynosure Bridge - OpenAI API-совместимый прокси для Claude MAX.
            
            ВАЖНО: 
            - Используешь Claude MAX подписку через локальный прокси
            - API endpoint: ${{ needs.start-proxy.outputs.proxy-url }}
            - Все запросы проходят через наш Cynosure Bridge
            - Отвечай на русском языке
            
            Проект: TypeScript/Node.js приложение с Fastify сервером
            Цель: Обеспечить совместимость с OpenAI API для Claude
          
          # Разрешенные инструменты  
          allowed_tools: |
            Edit,
            Replace,
            Bash(npm install),
            Bash(npm run test),
            Bash(npm run lint),
            Bash(npm run build),
            Bash(npm run typecheck)
            
          # Кастомные переменные окружения
          claude_env: |
            NODE_ENV: development
            CYNOSURE_PROXY_URL: ${{ needs.start-proxy.outputs.proxy-url }}
            OPENAI_API_BASE: ${{ needs.start-proxy.outputs.proxy-url }}
            
          # Прямой промпт для workflow_dispatch
          direct_prompt: ${{ github.event.inputs.task || '' }}

  # Очистка ресурсов
  cleanup:
    needs: [start-proxy, claude-response]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Cleanup Proxy
        run: |
          echo "🧹 Очищаем ресурсы..."
          # Останавливаем все процессы node
          pkill -f "npm start" || echo "Процессы уже остановлены"
          echo "✅ Очистка завершена"