name: Cynosure Bridge Local Test
on:
  workflow_dispatch:
  push:
jobs:
  cload-code-local:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Call Cynosure Bridge API (localhost)
        run: |
          curl -X POST http://localhost:3000/v1 \
            -H "Content-Type: application/json" \
            -d '{"test": "ping"}'